#!/usr/bin/env python
# ----------------------------------------------------------------------------
# convertdb
# ----------------------------------------------------------------------------
# Copyright (c) 2010 Skye Nott
# See LICENSE for details.
#
# This script will convert old telechat-ng account and password databases to
# the new telechat-py style database.

import sys
import anydbm
import whichdb

if len(sys.argv) < 2:
    print "usage:", sys.argv[0], "[old-acct]"
    sys.exit(1)

fn = sys.argv[1]
print "opening", fn, "type", whichdb.whichdb(fn)
db = anydbm.open(fn, 'r')

k = db.firstkey()
while k != None:
    print k
    k = db.nextkey(k)

db.close()
